# Generated by Django 3.0.8 on 2020-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200805_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soinsList', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
