# Generated by Django 3.0.8 on 2020-08-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='comment',
            new_name='Commentaire',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='soinsList',
            new_name='Soins',
        ),
        migrations.CreateModel(
            name='ClientsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='Client',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.ClientsList'),
        ),
    ]
