# Generated by Django 3.0.8 on 2020-08-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200809_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='Client',
        ),
    ]
