# Generated by Django 3.0.8 on 2020-08-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reservations_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsList',
        ),
    ]
