# Generated by Django 3.0.8 on 2020-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='soins',
            field=models.TextField(blank=True),
        ),
    ]
