# Generated by Django 3.0.8 on 2020-08-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0007_auto_20200809_1937'),
        ('users', '0014_user_soins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='soins',
        ),
        migrations.AddField(
            model_name='user',
            name='soins',
            field=models.ManyToManyField(to='soins.SoinsSelect'),
        ),
    ]
