# Generated by Django 3.0.8 on 2020-08-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200810_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='soins',
        ),
        migrations.AddField(
            model_name='user',
            name='soins',
            field=models.TextField(blank=True),
        ),
    ]
