# Generated by Django 3.0.8 on 2020-08-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200810_0129'),
    ]

    operations = [

    ]
