# Generated by Django 3.0.8 on 2020-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200810_1813'),
    ]

    operations = [

        migrations.AddField(
            model_name='soinslist',
            name='liste',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='soins',
            field=models.CharField(blank=True, max_length=254),
        ),

    ]
