# Generated by Django 3.0.5 on 2020-08-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200813_1707'),
    ]

    operations = [

    ]
