# Generated by Django 3.0.5 on 2020-08-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200814_0316'),
    ]

    operations = [

    ]
