# Generated by Django 3.0.5 on 2021-01-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200814_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='historique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Historique'),
        ),
        migrations.AlterField(
            model_name='soinslist',
            name='soin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Soins'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateNaiss',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fidelity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
