# Generated by Django 3.0.5 on 2021-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
