# Generated by Django 3.0.5 on 2021-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210109_1850'),
    ]

    operations = [

    ]
