# Generated by Django 3.0.5 on 2021-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispo',
            name='Hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispo',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
