# Generated by Django 3.0.8 on 2020-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionsCils', models.CharField(max_length=100)),
                ('lashLift', models.CharField(max_length=100)),
                ('lashLiftTeinture', models.CharField(max_length=100)),
                ('browLift', models.CharField(max_length=100)),
                ('browLift3dFiller', models.CharField(max_length=100)),
                ('browliftTeinture', models.CharField(max_length=100)),
                ('browlifthenne', models.CharField(max_length=100)),
                ('browlif3dTeinture', models.CharField(max_length=100)),
                ('browlif3dhenne', models.CharField(max_length=100)),
                ('hennaBrow', models.CharField(max_length=100)),
                ('teinture', models.CharField(max_length=100)),
                ('epilationSourcil', models.CharField(max_length=100)),
                ('soin3d', models.CharField(max_length=100)),
            ],
        ),
    ]
