# Generated by Django 3.0.8 on 2020-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoinsSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionsCils', models.BooleanField(default=False)),
                ('lashLift', models.BooleanField(default=False)),
                ('lashLiftTeinture', models.BooleanField(default=False)),
                ('browLift', models.BooleanField(default=False)),
                ('browLift3dFiller', models.BooleanField(default=False)),
                ('browliftTeinture', models.BooleanField(default=False)),
                ('browlifthenne', models.BooleanField(default=False)),
                ('browlif3dTeinture', models.BooleanField(default=False)),
                ('browlif3dhenne', models.BooleanField(default=False)),
                ('hennaBrow', models.BooleanField(default=False)),
                ('teinture', models.BooleanField(default=False)),
                ('epilationSourcil', models.BooleanField(default=False)),
                ('soin3d', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Soins',
        ),
    ]
