# Generated by Django 3.0.8 on 2020-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_auto_20200807_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soinsselect',
            name='extensionsCils',
            field=models.BooleanField(default=True),
        ),
    ]
