# Generated by Django 3.0.8 on 2020-08-09 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soins', '0005_auto_20200809_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichesClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(default='')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Soins', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soins.SoinsSelect')),
            ],
        ),
    ]
