# Generated by Django 3.0.5 on 2020-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0007_auto_20200809_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soinsselect',
            name='extensionsCils',
            field=models.BooleanField(default=False),
        ),
    ]
