# Generated by Django 3.0.5 on 2021-08-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0008_auto_20200813_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soinsselect',
            name='date',
        ),
    ]
