# Generated by Django 3.0.5 on 2021-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0009_remove_soinsselect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soinsselect',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
