# Generated by Django 3.0.8 on 2020-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoPromo', models.ImageField(upload_to='ajouter_une_image')),
                ('photoNoPromo', models.ImageField(upload_to='ajouter_une_image')),
                ('isPromo', models.BooleanField()),
            ],
        ),
    ]
