# Generated by Django 3.0.8 on 2020-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Promo', 'verbose_name_plural': 'Promo'},
        ),
        migrations.RemoveField(
            model_name='promo',
            name='isPromo',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='photoNoPromo',
        ),
        migrations.AddField(
            model_name='promo',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Promo'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='photoPromo',
            field=models.ImageField(blank=True, upload_to='image_promo'),
        ),
    ]
