# Generated by Django 3.0.8 on 2020-08-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0002_auto_20200807_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={},
        ),
    ]
