# Generated by Django 3.0.5 on 2021-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0006_auto_20200814_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photoPromo',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='photoPromo'),
        ),
    ]
