# Generated by Django 3.0.8 on 2020-08-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200809_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientslist',
            old_name='clientsName',
            new_name='clients',
        ),
    ]
